# ===========================================
# PVC : Persistent Volume Claims
# ===========================================

# Base de donn√©es MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
  labels:
    app: wave-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath

---

# Cache Laravel (bootstrap/cache)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-cache-pvc
  labels:
    app: wave-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---

# Storage Laravel (storage/)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wave-storage-pvc
  labels:
    app: wave-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: microk8s-hostpath

---

# Redis data persistence
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  labels:
    app: wave-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
