# ===========================================
# SECRETS : Données sensibles (mots de passe)
# ===========================================
apiVersion: v1
kind: Secret
metadata:
  name: wave-secrets
type: Opaque
stringData:
  # Utiliser stringData pour éviter l'encodage base64 manuel
  MYSQL_ROOT_PASSWORD: "wave23"
  MYSQL_PASSWORD: "wave23"
  APP_KEY: "base64:votre-cle-laravel-ici"
  # Pour générer une clé: php artisan key:generate --show

