---
  - name: Installer Docker sur les Nodes
    hosts: serveurs
    become: true

    tasks:
    - name: Copier le script d'installation
      copy:
        src: ./docker-install.sh
        dest: /tmp/docker-install.sh
        mode: '0755'

    - name: Exécuter le script
      command: /bin/bash /tmp/docker-install.sh

    - name: Supprimer le script
      file:
        path: /tmp/docker-install.sh
        state: absent

    - name: Vérifier si Docker est installé
      command: docker --version
      register: docker_version
      changed_when: false
      failed_when: false

    - name: Afficher la version de Docker
      debug:
        msg: "Version de Docker installée: {{ docker_version.stdout }}"
      when: docker_version.rc == 0

  - name: Installer Git sur les hôtes
    hosts: serveurs
    become: true

    tasks:
    - name: Installer Git sur Ubuntu/Debian
      apt:
        name: git
        state: present

  - name: Installer Zabbix avec Docker Compose
    hosts: Monitoring
    become: true
    tasks:
      - name: Créer un répertoire pour le docker-compose
        file:
          path: /home/monitoring
          state: directory

      - name: Cloner le dépôt Zabbix et Grafana Docker
        git:
          repo: https://github.com/akmalovaa/zabbix-docker.git
          dest: /home/monitoring
          update: yes

      - name: Démarrer les services avec Docker Compose
        command:
          cmd: docker compose up -d
          chdir: /home/monitoring

  - name: Installer Jenkins et SonarQube
    hosts: CI-CD
    become: true
    tasks:
      - name: Créer un répertoire pour le docker-compose
        file:
          path: /home/devtools
          state: directory

      - name: Copier le fichier docker-compose.yml
        copy:
          src: ./docker-compose.yml
          dest: /home/devtools/docker-compose.yml

      - name: Démarrer les services Docker Compose
        command: docker compose up -d
        args:
          chdir: /home/devtools/
